// Package identity manages the age identities (key files) that SOPS uses to decrypt secrets.
package identity

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"time"

	"filippo.io/age"
	"go.uber.org/zap"

	"github.com/TimCares/go-dockerctl"
	"github.com/TimCares/go-dockerctl/internal/config"
)

const defaultAgeKeyFileSubpath = "sops/age/keys.txt"

func checkKeyFileExists(identityPath string) (bool, error) {
	_, err := os.Stat(identityPath)
	if err == nil {
		return true, nil
	}
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	return false, fmt.Errorf("checking if key file exists: %w", err)
}

func getRecipientFromExistingIdentity(identityPath string) (string, error) {
	b, err := os.ReadFile(identityPath)
	if err != nil {
		return "", fmt.Errorf("found existing identity, but could not read it: %w", err)
	}

	// age errors embed the offending line on parsing errors, which may contain the private key.
	safeError := fmt.Errorf("found existing identity at %s, but encountered an error when parsing the recipient", identityPath)

	identities, err := age.ParseIdentities(bytes.NewReader(b))
	if err != nil {
		return "", safeError
	}

	for _, id := range identities {
		if x25519, ok := id.(*age.X25519Identity); ok {
			return x25519.Recipient().String(), nil
		}
	}

	return "", safeError
}

func makeKeyFileContents(identity *age.X25519Identity) []byte {
	timestamp := time.Now().Format("2006-01-02 15:04:05 MST")

	keyFileContents := fmt.Sprintf(
		"# Generated by dockerctl %s\n# Timestamp %s\n# public key: %s\n%s\n",
		dockerctl.Version,
		timestamp,
		identity.Recipient().String(),
		identity.String(),
	)

	return []byte(keyFileContents)
}

func writeKeyFile(identityPath string, data []byte) error {
	f, err := os.OpenFile(identityPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return fmt.Errorf("creating key file: %w", err)
	}

	_, writeErr := f.Write(data)
	closeErr := f.Close()
	if err := errors.Join(writeErr, closeErr); err != nil {
		if removeErr := os.Remove(identityPath); removeErr != nil { // Do not surface error as there is nothing we can do.
			zap.L().Debug("could not remove private key file after writing failed", zap.String("file", identityPath))
		}
		return fmt.Errorf("writing key file: %w", err)
	}

	return nil
}

// MaybeCreateNewSOPSIdentity returns the recipient (public key) of the identity at identityPath,
// generating a new identity first if none exists.
func MaybeCreateNewSOPSIdentity(identityPath string) (string, error) {
	fileExists, err := checkKeyFileExists(identityPath)
	if err != nil {
		return "", err
	}

	if fileExists {
		recipient, err := getRecipientFromExistingIdentity(identityPath)
		if err != nil {
			return "", err
		}
		zap.L().Info("Identity already exists", zap.String("recipient", recipient), zap.String("file", identityPath))
		return recipient, nil
	}

	identity, err := age.GenerateX25519Identity()
	if err != nil {
		return "", fmt.Errorf("generating identity: %w", err)
	}

	parent := filepath.Dir(identityPath)
	if err := os.MkdirAll(parent, 0o700); err != nil {
		return "", fmt.Errorf("creating parent dirs of key file: %w", err)
	}

	if err := writeKeyFile(identityPath, makeKeyFileContents(identity)); err != nil {
		return "", err
	}

	recipient := identity.Recipient().String()
	zap.L().Info(
		"generated new identity, add recipient to your .sops.yaml",
		zap.String("recipient", recipient),
		zap.String("identityFile", identityPath),
	)

	return recipient, nil
}

// sopsUserConfigDir mirrors how SOPS locates its config dir for age keys.
func sopsUserConfigDir() (string, error) {
	if runtime.GOOS == "darwin" {
		if dir := os.Getenv("XDG_CONFIG_HOME"); dir != "" {
			return dir, nil
		}
	}
	return os.UserConfigDir()
}

// GetSOPSIdentityPath returns the path of the age key file SOPS should use.
func GetSOPSIdentityPath(cfg *config.Config) (string, error) {
	userConfigDir, err := sopsUserConfigDir()
	if err != nil {
		return "", fmt.Errorf("determining user config dir: %w", err)
	}
	if cfg.ManageSOPSIdentities {
		return filepath.Join(userConfigDir, cfg.Name, cfg.Runtime.ActiveEnv, defaultAgeKeyFileSubpath), nil
	}
	return filepath.Join(userConfigDir, defaultAgeKeyFileSubpath), nil
}
