package identity

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"filippo.io/age"
	"go.uber.org/zap"

	"github.com/TimCares/go-dockerctl"
	"github.com/TimCares/go-dockerctl/internal/config"
)

const defaultAgeKeyFileSubpath = "sops/age/keys.txt"

func checkKeyFileExists(identityPath string) (bool, error) {
	if _, err := os.Stat(identityPath); err == nil {
		return true, nil
	} else if os.IsNotExist(err) {
		return false, nil
	} else {
		zap.L().Error("error when checking if key file already exists", zap.String("identityPath", identityPath), zap.Error(err))
		return false, err
	}
}

func getRecipientFromExistingIdentity(identityPath string) (*string, error) {
	b, err := os.ReadFile(identityPath)
	if err != nil {
		zap.L().Error("found existing identity, but encountered an error when reading the file", zap.String("file", identityPath))
		return nil, err
	}

	// age errors embed the offending line on parsing errors, which may contain the private key.
	safeError := errors.New("found existing identity, but encountered an error when parsing the recipient")

	identities, err := age.ParseIdentities(bytes.NewReader(b))
	if err != nil {
		zap.L().Error(safeError.Error(), zap.String("file", identityPath))
		return nil, safeError
	}

	for _, id := range identities {
		if x25519, ok := id.(*age.X25519Identity); ok {
			recipientString := x25519.Recipient().String()
			return &recipientString, nil
		}
	}

	zap.L().Error(safeError.Error(), zap.String("file", identityPath))
	return nil, safeError
}

func makeKeyFileContents(identity *age.X25519Identity) []byte {
	timestamp := time.Now().Format("2006-01-02 15:04:05 MST")

	keyFileContents := fmt.Sprintf(
		"# Generated by dockerctl %s\n# Timestamp %s\n# public key: %s\n%s\n",
		dockerctl.Version,
		timestamp,
		identity.Recipient().String(),
		identity.String(),
	)

	return []byte(keyFileContents)
}

func MaybeCreateNewSOPSIdentity(identityPath string) (*string, error) {
	fileExists, err := checkKeyFileExists(identityPath)
	if err != nil {
		return nil, err
	}

	if fileExists {
		recipientString, err := getRecipientFromExistingIdentity(identityPath)
		if err != nil {
			return nil, err
		}
		zap.L().Info("Identity already exists", zap.String("recipient", *recipientString), zap.String("file", identityPath))
		return recipientString, nil
	}

	// Generate new identity:

	identity, err := age.GenerateX25519Identity()
	if err != nil {
		zap.L().Error("error generating identity", zap.Error(err))
		return nil, err
	}
	recipientString := identity.Recipient().String()

	parent := filepath.Dir(identityPath)
	if err := os.MkdirAll(parent, 0700); err != nil {
		zap.L().Error("error creating parent dirs of key file", zap.String("parent", parent), zap.Error(err))
		return nil, err
	}

	f, err := os.OpenFile(
		identityPath,
		os.O_WRONLY|os.O_CREATE|os.O_EXCL,
		0600,
	)
	if err != nil {
		zap.L().Error("error creating key file", zap.String("file", identityPath), zap.Error(err))
		return nil, err
	}
	defer f.Close()

	data := makeKeyFileContents(identity)

	if _, err := f.Write(data); err != nil {
		zap.L().Error("error writing key data to file", zap.String("file", identityPath), zap.Error(err))
		if removeErr := os.Remove(identityPath); removeErr != nil { // Do not surface error as there is nothing we can do.
			zap.L().Debug("could not remove private key file after writing failed", zap.String("file", identityPath))
		}
		return nil, err
	}

	zap.L().Info(
		"generated new identity, add recipient to your .sops.yaml",
		zap.String("recipient", recipientString),
		zap.String("identityFile", identityPath),
	)

	return &recipientString, nil
}

// Uses age.
func GetSOPSIdentityPath(config config.Config) string {
	userConfigDir := os.Getenv("XDG_CONFIG_HOME")
	if userConfigDir == "" {
		userConfigDir = os.Getenv("HOME")
	}
	if config.ManageSOPSIdentities {
		return filepath.Join(userConfigDir, config.Name, config.Runtime.ActiveEnv, defaultAgeKeyFileSubpath)
	} else {
		return filepath.Join(userConfigDir, defaultAgeKeyFileSubpath)
	}
}
